# Generated by Django 6.0.4 on 2026-04-30 10:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document_documentterm_term_delete_uploadedfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RenameField(
            model_name='document',
            old_name='file_name',
            new_name='original_file_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, max_length=500, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='documentterm',
            index=models.Index(fields=['term', 'document'], name='main_docume_term_id_0a1cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentterm',
            index=models.Index(fields=['document', 'term'], name='main_docume_documen_92cad2_idx'),
        ),
        migrations.AddField(
            model_name='termrelation',
            name='term1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_term1', to='main.term'),
        ),
        migrations.AddField(
            model_name='termrelation',
            name='term2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_term2', to='main.term'),
        ),
        migrations.AlterUniqueTogether(
            name='termrelation',
            unique_together={('term1', 'term2')},
        ),
    ]
